### ISSUE TITLE
Use browserify as a dev-dependency

### ISSUE THREAD

**Issue by rubennorte** [juliangruber/browser-run#12]
browser-run is the perfect tool to launch tests in a continuous integration environment, like Jenkins and Travis. We could save time, bandwidth and disk space (halt of the size of the installed package, 22 of 45 MB, corresponds to browserify) if instead of requiring browserify as a runtime dependency to bundle the `browser/reporter.js` file, it would be included that way in the published package.

I also think the package `utf8-stream` is only used in that file, so it could also be installed as a devDependency only.

Example package.json:

```json
{
  "scripts": {
    "prepublish": "browserify browser/reporter.js -o dist/reporter.js"
  },
  "devDependencies": {
    "browserify": "~5.9.3",
    "utf8-stream": "0.0.0"
  }
}
```

If you agree I can create a PR ;)

**Comment by juliangruber** [comment]
I totally agree :)
