### ISSUE TITLE
Works in everything EXCEPT Electron

### ISSUE THREAD

**Issue by ryanfields** [juliangruber/browser-run#135]
I don't know what I could be getting wrong in my setup, but I can't seem to make this work using Electron.

Running with `cat build/index.html | browser-run --input html --static build`

Folder structure is
```
build/
  bundle.js
  index.html

css/
  ... source files ...

html/
  ... source files ...

js/
  ... source files ...

node_modules/
  ... node modules ...

package.json
webpack.config.js
```

index.html is
```
<div id="app"></div>
<script type="text/javascript" src="/reporter.js"></script>
<script type="text/javascript" src="/bundle.js"></script>
```

I've stripped down my bundle so that the only code going into it is some babel runtime code and:
```
import test from 'tape'

test.onFinish(function(){
  window.close();
});

test('test ok', function (t) {
  t.ok(true)
  t.end()
})
```

If I use the -b or --port options, everything works as expected.  If I leave those options off, Electron tries to run but just outputs `SyntaxError: Unexpected token <` and immediately exits.

Adding `--basedir build` causes Electron to create a file called `.source.[timestamp].html` and the contents of that file are:

```
<body><script><div id="app"></div>
<script type="text/javascript" src="/reporter.js"></script>
<script type="text/javascript" src="/bundle.js"></script>
</script></body>
```

However, nothing is output and Electron just hangs until I hit Ctrl-C.

Meanwhile, using a browser (-b or --port), I get exactly the output I expect:

```
TAP version 13
# okay
ok 1 should be truthy

1..1
# tests 1
# pass  1

# ok
```

**Comment by nstanard** [comment]
My team had to target a specific version of browser-run after the build started failing where I work. It was kinda annoying but we did not file the issue. Thanks for taking the time and opening this. 

We added this to our package.json file as a workaround for the error message you are referencing.
`"browser-run": "3.4.0",`

**Comment by nstanard** [comment]
One of the developers I work with narrowed it down to:
https://github.com/juliangruber/browser-run/blob/master/lib/launch.js#L12

**Comment by juliangruber** [comment]
Oh, dang, yeah that only doesn't work in electron currently. Will get a fix out this week!

**Comment by juliangruber** [comment]
(will also add tests for this!)

**Comment by juliangruber** [comment]
can you check if 4.0.2 works for you?

**Comment by nstanard** [comment]
To test this I'd need to update my tape-run version from 2.1.4 -> 3.0.0. 🤔

**Comment by nstanard** [comment]
@juliangruber Removed browser-run from my package file and instead installed 3.0.0 of tape-run. I still got the same error though. 

`SyntaxError: Invalid or unexpected token`

**Comment by ryanfields** [comment]
It may be working now, but I'm not certain and the issue flipped.

I am able to complete a test run, but a bunch of my tests aren't running.  I went to rule out Electron itself as the problem but now --port and -b are doing what the Electron path perviously did.  With -b, the browser opens and then just waits for a server response forever.  When I connect via port I get the same behavior.  If the browser is waiting and I Ctrl-C browser-run, the browser immediately reports that it can't connect to the server, so I know it's trying to connect and run and there's just nothing responding.

**Comment by juliangruber** [comment]
> @juliangruber Removed browser-run from my package file and instead installed 3.0.0 of tape-run. I still got the same error though.
> 
> SyntaxError: Invalid or unexpected token

you could run this with browser-run@4.0.2 or tape-run@3.0.0. Also make sure to clean your npm cache before upgrading (`npm cache clean`) to make sure you get tu=he current versions.

One syntax error bug was fixed yesterday.

**Comment by tschant** [comment]
Update (I work with @nstanard): ran with tape-run@3.0.0 and browser-run@4.0.2 (after cache clean) and got `SyntaxError: Invalid or unexpected token` again, it seems to be hitting https://github.com/juliangruber/browser-run/commit/adb7c320f99ac14fa5c62369a5b42c340971162d#diff-8e402bf78d4c5f8a4fb797709e5bc7a3R13
We are using default (empty) options when running tape-run.

**Comment by juliangruber** [comment]
the `http://` protocol is back! (in the current version)
