### ISSUE TITLE
doesn't work with js code that contains a </script>

### ISSUE THREAD

**Issue by tyler-johnson** [juliangruber/browser-run#138]
I have an issue with browser-run where it will spit out a `SyntaxError: Invalid or unexpected token`. Originally I thought it had to do with #135, however after a lot of head bashing and finally running the `.source...` file in the browser directly I realized that the problem was a closing script tag located in the script.

This is an issue with injecting JavaScript directly into HTML as the browser is going to interpret a `</script>` literally, even if it appears in a string or something.

I don't know the best way to fix this, but perhaps the script can be encoded in the HTML file and then decoded and eval'd on the browser? Curious on your thoughts. Thanks!

**Comment by juliangruber** [comment]
can you try with the latest version? this should be fixed now

**Comment by fregante** [comment]
Closing for lack of response
