### ISSUE TITLE
Publish  4.1.1 to npm registry

### ISSUE THREAD

**Issue by yury-sannikov** [juliangruber/browser-run#142]
Hi @juliangruber, could you please publish 4.1.1 to NPM?
Looks like peers used to have 4.1.1 reference (https://github.com/juliangruber/tape-run/blob/master/package.json#L19 for instance) but now 4.1.1 is gone...

Thanks!

**Comment by juliangruber** [comment]
4.1.1 is up on npm, see https://www.npmjs.com/package/browser-run

If it still doesn't install for you, please open an issue on npm/npm.

**Comment by yury-sannikov** [comment]
Thanks!
