### ISSUE TITLE
node_modules\browser-run\index.js:4:22 Cannot resolve dependency

### ISSUE THREAD

**Issue by ghost** [juliangruber/browser-run#143]
In my console its telling me that it can't resolve dependency node_modules\browser-run\index.js:4:22, and in the browsers console its telling me that sax is not defined.

**Comment by ashnur** [comment]
Doesn't sound like an issue with browser-run itself, more like a build error. Can you elaborate more about what you are trying to do?

**Comment by juliangruber** [comment]
Can you also please post the full stack trace / console output?

**Comment by fregante** [comment]
This can be closed, the user is gone
