### ISSUE TITLE
Multiple arguments to window.console methods not printed to command line

### ISSUE THREAD

**Issue by btakita** [juliangruber/browser-run#15]
In `reporter.js`, it seems like only the first argument is written to the command line.

`ws.write(msg + '\n');`

```
    console[method] = function (msg) {
      ws.write(msg + '\n');
      if (old) old.apply(console, arguments);
      if (msg instanceof Error && typeof JSON != 'undefined') {
        ws.write(JSON.stringify(msg) + '\n'); 
      }
```

**Comment by btakita** [comment]
Something like the following would be better:

`ws.write(Array.prototype.slice.call(arguments, 1).join(" ") + '\n');`

**Comment by juliangruber** [comment]
yeah sounds good, would you mind creating a pull request?
