### ISSUE TITLE
Autoclose?

### ISSUE THREAD

**Issue by peteruithoven** [juliangruber/browser-run#21]
When using the cli, is there anyway to automatically close browsers after some task "finished"? 
Would it be possible to call something in javascript that browser-run picks up and have it stop itself? 

I'm using browser-run to run unit testing and when their done I'd like it to automatically close the browser again. 
(It now closes the browser when it stop the browser-run process (with ctrl+c)).

**Comment by juliangruber** [comment]
we can't automatically determine when something's done, but yeah, a `window.close()` could work! i'll try to come up with something

**Comment by juliangruber** [comment]
starting at `2.4.0`, calling `window.close()` in phantomjs (and possibly other browsers) will completely end the `browser-run` instance
