### ISSUE TITLE
Use local PhantomJS?

### ISSUE THREAD

**Issue by peteruithoven** [juliangruber/browser-run#22]
Currently the package requires a globally installed PhantomJS. There are situations where you'd like to pin the version to specific projects. It's also easier for people to use because it can get installed with other dependencies when `npm install` is called.

**Comment by juliangruber** [comment]
we've had that but the package was causing too many problems, seems like this is hard to do cross platform

**Comment by peteruithoven** [comment]
Thanks for clearing that up.
