### ISSUE TITLE
Add option to disable appending random string to js

### ISSUE THREAD

**Issue by neojski** [juliangruber/browser-run#27]
https://github.com/juliangruber/browser-run/blob/b2f008d641eb1cbe2bc45c9e9a677a2181e39324/static/index.html#L10

It breaks breakpoints if I want to debug test manually.

**Comment by juliangruber** [comment]
i did that to disable any caching mechanisms browsers might have in place. but i didn't see then that i can do the same with headers, i'll come up with a pull request.

**Comment by juliangruber** [comment]
published as 2.4.1
