### ISSUE TITLE
Browser-run causing tape-run tests to hang

### ISSUE THREAD

**Issue by haydn** [juliangruber/browser-run#35]
This is probably related to #33 or #28. It took me a while to track down the solution so I'm making this issue to hopefully help others searching for the answer.

I had a `package.json` file with something like this:

```json
{
  ...
  "devDependencies": {
    "tape-run": "^1.1.0"
  }
  ...
}
```

When I ran my tests they'd hang unexpectedly causing timeouts on Travis CI. I had to specify an older version of `browser-run` to get them to run again:

```json
{
  ...
  "devDependencies": {
    "browser-run": "2.5.0",
    "tape-run": "^1.1.0"
  }
  ...
}
```

For more details:

https://travis-ci.org/haydn/json-api-store/builds/83237200

**Comment by juliangruber** [comment]
what is a failing build i should look at?

**Comment by haydn** [comment]
@juliangruber This build failed on October 1st:

https://travis-ci.org/haydn/json-api-store/builds/83067915

However, the commit just before that had passed on September 23rd:

https://travis-ci.org/haydn/json-api-store/builds/81694961

**Comment by juliangruber** [comment]
relevant: https://github.com/juliangruber/browser-run/issues/39

**Comment by juliangruber** [comment]
the new version using electron fixes a lot of issues, this should be gone
