### ISSUE TITLE
Example with watch

### ISSUE THREAD

**Issue by colindresj** [juliangruber/browser-run#60]
Is there some way of getting this to work while watching for file changes?

Currently I'm killing the process, then starting a new one on each change, but it feels a bit brute. Any ideas?

**Comment by juliangruber** [comment]
i'm assuming you're using browserify, so try this:

```bash
$ watchify main.js -o 'browser-run'
```

**Comment by colindresj** [comment]
Sorry, should have specified that I've actually got a pre-built bundle which I stream into a browser-run child process's `stdin`. I'm using chokidar for watching.

**Comment by juliangruber** [comment]
you can use browser-run's api for this:

```js
chokidar.on('update', function(){
  buildBundle().pipe(run())
});
```

does that work for you?

**Comment by colindresj** [comment]
Yeah that's pretty much exactly what I'm doing, except I get an occupied port if I leave it like this, so I have to something like this:

```js
chokidar.on('update', () => {
  if (browser) browser.stop();
  browser = run({ port });
  buildBundle().pipe(browser);
});
```

I'm ok with doing that, but was just wondering if there was a more elegant solution.

**Comment by colindresj** [comment]
I'll close this issue, since this already works, and it's more a feedback thing now

**Comment by juliangruber** [comment]
I think this is perfectly elegant. You can remove the browser.stop() if at the end your bundle executes window.close()

**Comment by colindresj** [comment]
Great suggestion thanks. Is there any way to tell the browser to refresh? If I pipe in "window.location.reload", I get stuck in an infinite refresh loop.
